# Development environment overrides
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-new
      dockerfile: Dockerfile.dev  # Use development Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
        VITE_ENVIRONMENT: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend-new:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"  # Development port
    depends_on:
      - backend 