services:
  redis-security-test:
    image: redis:7.2.5-alpine
    container_name: meme-maker-redis-security-test
    restart: unless-stopped
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - security-test-network

  backend-security-test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: meme-maker-backend-security-test
    restart: unless-stopped
    depends_on:
      redis-security-test:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis-security-test:6379
      - ENVIRONMENT=security-testing
      - CLIPS_DIR=/app/clips
      - BASE_URL=http://localhost:8001
      - CORS_ORIGINS=["http://localhost:3001","http://localhost:8081"]
      - INSTAGRAM_COOKIES_B64=${INSTAGRAM_COOKIES_B64}
      # Security testing specific variables
      - SECURITY_TEST_MODE=true
      - LOG_LEVEL=DEBUG
      - RATE_LIMIT_DISABLED=true  # For testing rate limiting bypasses
    ports:
      - "8001:8000"  # Different port to avoid conflicts
    volumes:
      - ./storage-security-test:/app/clips
      - ./logs-security-test:/app/logs
    networks:
      - security-test-network

  frontend-security-test:
    build:
      context: ./frontend-new
      dockerfile: ../frontend/Dockerfile.dev
    container_name: meme-maker-frontend-security-test
    restart: unless-stopped
    depends_on:
      - backend-security-test
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
      - NODE_ENV=development
      - VITE_ENVIRONMENT=security-testing
    ports:
      - "3001:3000"  # Different port to avoid conflicts
    volumes:
      - ./frontend-new:/app
      - /app/node_modules
    networks:
      - security-test-network
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # Worker process for testing yt-dlp security
  worker-security-test:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: meme-maker-worker-security-test
    restart: unless-stopped
    depends_on:
      redis-security-test:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis-security-test:6379
      - ENVIRONMENT=security-testing
      - CLIPS_DIR=/app/clips
      - SECURITY_TEST_MODE=true
      - LOG_LEVEL=DEBUG
      # Enhanced sandboxing for security testing
      - YTDLP_SANDBOX_MODE=strict
      - YTDLP_MAX_MEMORY=256m
      - YTDLP_TIMEOUT=30
    volumes:
      - ./storage-security-test:/app/clips
      - ./logs-security-test:/app/logs
    networks:
      - security-test-network
    # Security-focused resource limits
    mem_limit: 512m
    cpus: 0.5
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

networks:
  security-test-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

volumes:
  storage-security-test:
  logs-security-test: 