# 🔒 SIMPLIFIED SECURITY-HARDENED TEST ENVIRONMENT
# Based on security-test environment with T-002 container escape protections

services:
  redis-security-test:
    image: redis:7.2.5-alpine
    container_name: meme-maker-redis-security-test-hardened
    restart: unless-stopped
    
    # 🔒 CONTAINER ESCAPE PROTECTIONS
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID  
      - SETGID
    
    # 🔒 RESOURCE LIMITS
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    
    ports:
      - "6380:6379"
    
    command: ["redis-server"]
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    
    networks:
      - security-test-network

  backend-security-test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: meme-maker-backend-security-test-hardened
    restart: unless-stopped
    
    depends_on:
      redis-security-test:
        condition: service_healthy
    
    # 🔒 CONTAINER ESCAPE PROTECTIONS
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID
    
    # 🔒 RESOURCE LIMITS
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    
    environment:
      - REDIS_URL=redis://redis-security-test:6379
      - ENVIRONMENT=security-test
      - CLIPS_DIR=/app/clips
      - BASE_URL=http://localhost:8001
      - CORS_ORIGINS=["http://localhost:3001", "http://localhost:8001"]
      - INSTAGRAM_COOKIES_B64=${INSTAGRAM_COOKIES_B64}
    
    ports:
      - "8001:8000"
    
    volumes:
      - ./storage-security-test:/app/clips
    
    command: >
      sh -c "
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1 || 
        (echo '❌ Backend failed to start. Review logs above for errors.' && exit 1)
      "
    
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - security-test-network

  frontend-security-test:
    build:
      context: ./frontend-new
      dockerfile: Dockerfile
    container_name: meme-maker-frontend-security-test-hardened
    restart: unless-stopped
    
    depends_on:
      backend-security-test:
        condition: service_healthy
    
    # 🔒 CONTAINER ESCAPE PROTECTIONS
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID
    
    # 🔒 RESOURCE LIMITS
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    
    ports:
      - "3001:80"
    
    environment:
      - NODE_ENV=production
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - security-test-network

  worker-security-test:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: meme-maker-worker-security-test-hardened
    restart: unless-stopped
    
    depends_on:
      redis-security-test:
        condition: service_healthy
      backend-security-test:
        condition: service_healthy
    
    # 🔒 ENHANCED CONTAINER ESCAPE PROTECTIONS (Most Critical)
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    
    # 🔒 STRICT RESOURCE LIMITS
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    
    environment:
      - REDIS_URL=redis://redis-security-test:6379
      - CLIPS_DIR=/app/clips
      - BASE_URL=http://localhost:8001
      - ENVIRONMENT=security-test
      - INSTAGRAM_COOKIES_B64=${INSTAGRAM_COOKIES_B64}
      # 🔒 yt-dlp SECURITY RESTRICTIONS
      - YTDLP_EXTRACT_FLAT=true
      - YTDLP_NO_PLAYLIST=true
      - YTDLP_RESTRICT_FILENAMES=true
      - YTDLP_MAX_FILESIZE=50M
    
    volumes:
      - ./storage-security-test:/app/clips
    
    healthcheck:
      test: ["CMD", "python", "-c", "import redis, os; redis.Redis.from_url(os.getenv('REDIS_URL')).ping()"]
      interval: 15s
      timeout: 5s
      start_period: 60s
      retries: 3
    
    networks:
      - security-test-network

# 🔒 ISOLATED SECURITY TEST NETWORK
networks:
  security-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24 