services:
  redis:
    image: redis:7.2.5-alpine
    container_name: meme-maker-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: meme-maker-backend
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - clips-storage:/app/clips
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: meme-maker-worker
    depends_on:
      - redis
      - backend
    volumes:
      - clips-storage:/app/clips

  prometheus:
    image: prom/prometheus
    container_name: meme-maker-prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: meme-maker-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  clips-storage:
  prometheus-data:
  grafana-data:
