services:
  redis:
    image: redis:7.2.5-alpine
    container_name: meme-maker-redis-dev
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: meme-maker-backend-dev
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - clips-storage:/app/clips
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: meme-maker-frontend-dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: meme-maker-worker-dev
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - clips-storage:/app/clips
    command: ["python", "/app/worker/main.py"]

volumes:
  clips-storage: 