services:
  redis:
    image: redis:7.2.5-alpine
    container_name: meme-maker-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: meme-maker-backend-dev
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - ENVIRONMENT=development
      - STORAGE_BACKEND=local
      - CLIPS_DIR=/app/clips
      - BASE_URL=http://localhost:8000
    ports:
      - "8000:8000"
    volumes:
      - clips-storage:/app/clips
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend-new
      dockerfile: Dockerfile.dev
    container_name: meme-maker-frontend-dev
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_BASE_URL=ws://localhost:8000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-new:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: meme-maker-worker-dev
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - STORAGE_BACKEND=local
      - CLIPS_DIR=/app/clips
    volumes:
      - clips-storage:/app/clips
    command: ["python", "/app/worker/main.py"]

volumes:
  clips-storage:
    driver: local 