name: Deploy to Lightsail Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          set -e
          # Navigate to the project directory
          cd ~/Meme-Maker
          
          # Fetch the latest changes and forcefully reset the local branch
          # This ensures the server is an exact mirror of the repository
          git fetch origin
          git reset --hard origin/master
          echo "✅ Force-pulled latest changes from GitHub"
          
          # Stop the current services and remove volumes
          docker-compose down --volumes
          echo "✅ Services stopped and volumes removed"
          
          # Rebuild all services without cache to ensure fresh build
          docker-compose build --no-cache
          echo "✅ Containers rebuilt"
          
          # Start the services in detached mode
          docker-compose up -d
          echo "✅ Services started"
          
          # Clean up unused Docker images and volumes
          docker system prune -af
          echo "✅ Docker system pruned"
          
          echo "🚀 Deployment to production successful!" 